apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: com.hammerspace.csi
spec:
  attachRequired: true
  podInfoOnMount: false
  fsGroupPolicy: File # added in Kubernetes 1.19, this field is GA as of Kubernetes 1.23
  volumeLifecycleModes: # added in Kubernetes 1.16, this field is beta
    - Persistent
 
