---
apiVersion: v1
kind: Namespace
metadata:
  name: hammerspace
  labels:
    name: hammerspace
    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alpine-dynamic
  namespace: hammerspace
  labels:
    app: csi-testing
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: hs-storage-share

---
kind: Pod
apiVersion: v1
metadata:
  name: alpine-dynamic
  namespace: hammerspace
  labels:
    app: csi-testing
spec:
  containers:
    - image: alpine:latest
      name: alpine
      command:
        - "/bin/sh"
        - "-c"
        - set -euo pipefail; while true; do echo "alpine-dynamic-1 $(date)" >> /mnt/nfs/alpine-dynamic; sleep 10; done
      volumeMounts:
        - name: vol1
          mountPath: "/mnt/nfs"
          readOnly: false
  volumes:
    - name: vol1
      persistentVolumeClaim:
        claimName: alpine-dynamic