---
apiVersion: v1
kind: Namespace
metadata:
  name: hs-csi-file-backed
  labels:
    name: hs-csi-file-backed
    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alpine-dynamic-file-backed
  namespace: hs-csi-file-backed
  labels:
    app: csi-file-backed
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: hs-storage-file-backed

---
kind: Pod
apiVersion: v1
metadata:
  name: alpine-dynamic-file
  namespace: hs-csi-file-backed
  labels:
    app: csi-file-backed
spec:
  containers:
    - image: alpine:latest
      name: alpine
      command:
        - "/bin/sh"
        - "-c"
        - set -euo pipefail; while true; do echo "alpine-dynamic-1 $(date)" >> /mnt/blockdev/alpine-dynamic-file-backed; sleep 10; done
      volumeMounts:
        - name: vol1
          mountPath: "/mnt/blockdev"
          readOnly: false
  volumes:
    - name: vol1
      persistentVolumeClaim:
        claimName: alpine-dynamic-file-backed