---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: pptest2
  name: alpine-share-2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pptest2
  volumeMode: Filesystem
  storageClassName: hs-storage
---
kind: Pod
apiVersion: v1
metadata:
  name: alpine-ns2
  namespace: pptest2
spec:
  containers:
    - image: alpine:latest
      name: alpine
      command:
        - "/bin/sh"
        - "-c"
        - set -euo pipefail; while true; do echo "alpine-share-2 $(date)" >> /mnt/nfs/outfile; sleep 1; done
      volumeMounts:
        - name: vol1
          mountPath: "/mnt/nfs"
          readOnly: false
  volumes:
    - name: vol1
      persistentVolumeClaim:
        claimName: alpine-share-2