---
kind: Pod
apiVersion: v1
metadata:
  name: alpine-nfs-3
  namespace: hammerspace
spec:
  containers:
    - image: alpine:latest
      name: alpine
      command:
        - "/bin/sh"
        - "-c"
        - set -euo pipefail; while true; do echo $(date) >> /mnt/nfs/outfile; sleep 1; done
      volumeMounts:
        - name: vol1
          mountPath: "/mnt/nfs"
          readOnly: false
  volumes:
    - name: vol1
      persistentVolumeClaim:
        claimName: mount-options