---
kind: Pod
apiVersion: v1
metadata:
  name: nginx-nfs-2
spec:
  containers:
    - image: nginx:latest
      name: nginx
      command:
        - "/bin/bash"
        - "-c"
        - set -euo pipefail; while true; do echo $(date) >> /mnt/nfs/outfile; sleep 1; done
      volumeMounts:
        - name: hs-search
          mountPath: "/mnt/nfs"
          readOnly: false
  volumes:
    - name: hs-search
      persistentVolumeClaim:
        claimName: mount-options